# This is the name that will appear in GitHub Actions

name: RAG Gemini Chat CI/CD

on:

  # Run the workflow whenever code is pushed
  # to the parveen-rag-app branch.
  push:
    branches:
      - parveen-rag-app


jobs:

  # CI Job
  build-and-test:

    # GitHub gives us a temporary Ubuntu machine
    # to execute these commands.
    runs-on: ubuntu-latest


    steps:

      # ------------------------------------------------------
      # 1. CHECKOUT CODE
      # ------------------------------------------------------

      # This downloads our GitHub repository
      # into the GitHub Actions machine.
      #
      # Without this, GitHub Actions doesn't have
      # our source code.

      - name: Checkout repository
        uses: actions/checkout@v4


      # ------------------------------------------------------
      # 2. INSTALL NODE.JS
      # ------------------------------------------------------

      # Our application is a Next.js application,
      # so GitHub needs Node.js.

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      # ------------------------------------------------------
      # 3. INSTALL DEPENDENCIES
      # ------------------------------------------------------

      # package-lock.json exists in our project.
      #
      # npm ci:
      #   - installs dependencies
      #   - uses package-lock.json
      #   - is recommended for CI environments

      - name: Install dependencies
        run: npm ci


      # ------------------------------------------------------
      # 4. BUILD NEXT.JS APPLICATION
      # ------------------------------------------------------

      - name: Build Next.js application
        run: npm run build


      # ------------------------------------------------------
      # 5. BUILD DOCKER IMAGE
      # ------------------------------------------------------

      - name: Build Docker image
        run: docker build -t rag-gemini-chat .